<a href="https://colab.research.google.com/github/Dhatrikowthavarapu/Machine-Learning/blob/main/ML_Bascis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np 

**Importing LogisticRegression**

In [ ]:
from sklearn.linear_model import LogisticRegression

**Downloading csv file from colab drive**


In [ ]:
data_path = "/content/drive/MyDrive/diabetes.csv" 
df = pd.read_csv(data_path)

In [ ]:
df.head(10)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   
5            5      116             74              0        0  25.6   
6            3       78             50             32       88  31.0   
7           10      115              0              0        0  35.3   
8            2      197             70             45      543  30.5   
9            8      125             96              0        0   0.0   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
5                     0.201   30        0  
6                     0.248   26        1  
7                     0.134   29        0  
8                     0.158   53        1  
9                     0.232   54        1

In [ ]:
df.shape

(768, 9)

In [ ]:
x=df.iloc[:,:-1]
y = df['Outcome'].values

In [ ]:

type(x)

pandas.core.frame.DataFrame

In [ ]:
type(y)

numpy.ndarray

In [ ]:
x.shape , y.shape

((768, 8), (768,))

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=12)

In [ ]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((614, 8), (154, 8), (614,), (154,))

In [ ]:
model=LogisticRegression()
model.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [ ]:
y_pred=model.predict(x_test)

**METRICS**

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
print(classification_report(y_test,y_pred,digits=4))

              precision    recall  f1-score   support

           0     0.8125    0.9192    0.8626        99
           1     0.8095    0.6182    0.7010        55

    accuracy                         0.8117       154
   macro avg     0.8110    0.7687    0.7818       154
weighted avg     0.8114    0.8117    0.8049       154



In [ ]:
print(confusion_matrix(y_test,y_pred))

[[91  8]
 [21 34]]


**Desicion Tree**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[81 18]
 [19 36]]


In [ ]:
print(classification_report(y_test,y_pred,digits=4))

              precision    recall  f1-score   support

           0     0.8100    0.8182    0.8141        99
           1     0.6667    0.6545    0.6606        55

    accuracy                         0.7597       154
   macro avg     0.7383    0.7364    0.7373       154
weighted avg     0.7588    0.7597    0.7592       154



**Naive Bayes**

In [ ]:
from sklearn.naive_bayes import GaussianNB
dt=GaussianNB()
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[89 10]
 [22 33]]


In [ ]:
print(classification_report(y_test,y_pred,digits=4))

              precision    recall  f1-score   support

           0     0.8018    0.8990    0.8476        99
           1     0.7674    0.6000    0.6735        55

    accuracy                         0.7922       154
   macro avg     0.7846    0.7495    0.7605       154
weighted avg     0.7895    0.7922    0.7854       154



**K Neighbors Classifier**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
dt=KNeighborsClassifier(n_neighbors= 5)
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred,digits=4))

[[77 22]
 [27 28]]
              precision    recall  f1-score   support

           0     0.7404    0.7778    0.7586        99
           1     0.5600    0.5091    0.5333        55

    accuracy                         0.6818       154
   macro avg     0.6502    0.6434    0.6460       154
weighted avg     0.6760    0.6818    0.6782       154



In [ ]:
dt=KNeighborsClassifier(n_neighbors= 7)
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred,digits=4))

[[78 21]
 [25 30]]
              precision    recall  f1-score   support

           0     0.7573    0.7879    0.7723        99
           1     0.5882    0.5455    0.5660        55

    accuracy                         0.7013       154
   macro avg     0.6728    0.6667    0.6692       154
weighted avg     0.6969    0.7013    0.6986       154



In [ ]:
dt=KNeighborsClassifier(n_neighbors= 9)
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred,digits=4))

[[79 20]
 [24 31]]
              precision    recall  f1-score   support

           0     0.7670    0.7980    0.7822        99
           1     0.6078    0.5636    0.5849        55

    accuracy                         0.7143       154
   macro avg     0.6874    0.6808    0.6835       154
weighted avg     0.7102    0.7143    0.7117       154



**SVM**

In [ ]:
from sklearn.svm import SVC

In [ ]:
m1=SVC(kernel='linear')
m2=SVC(kernel='rbf')
m3=SVC(kernel='poly')

In [ ]:
dt=SVC(kernel='linear')
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred,digits=4))

[[90  9]
 [20 35]]
              precision    recall  f1-score   support

           0     0.8182    0.9091    0.8612        99
           1     0.7955    0.6364    0.7071        55

    accuracy                         0.8117       154
   macro avg     0.8068    0.7727    0.7842       154
weighted avg     0.8101    0.8117    0.8062       154



In [ ]:
dt=SVC(kernel='rbf')
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred,digits=4))

[[90  9]
 [26 29]]
              precision    recall  f1-score   support

           0     0.7759    0.9091    0.8372        99
           1     0.7632    0.5273    0.6237        55

    accuracy                         0.7727       154
   macro avg     0.7695    0.7182    0.7304       154
weighted avg     0.7713    0.7727    0.7609       154



In [ ]:
dt=SVC(kernel='poly')
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred,digits=4))

[[93  6]
 [27 28]]
              precision    recall  f1-score   support

           0     0.7750    0.9394    0.8493        99
           1     0.8235    0.5091    0.6292        55

    accuracy                         0.7857       154
   macro avg     0.7993    0.7242    0.7393       154
weighted avg     0.7923    0.7857    0.7707       154

